// Series + tornado display names — ported verbatim from app/streamlit_app.py
// (LABELS / TORNADO_LABELS). Copy is the user's; do not rewrite.
export const LABELS: Record<string, string> = {
  employed_M: 'Employed',
  on_ui_M: 'On unemployment insurance',
  exhausted_M: 'Exhausted UI (no benefits)',
  reabsorbed_M: 'Re-employed at lower wage',
  exited_M: 'Left labor force (SSDI)',
  induced_M: 'Laid off by demand shortfall',
  retired_M: 'Retired (natural attrition)',
  fed_deficit_abs_B: 'Federal deficit (absolute)',
  fed_revenue_B: 'Federal revenue',
  fed_deficit_B: 'Federal deficit change',
  fed_debt_B: 'Federal debt change (cumulative)',
  retained_profit_B: 'Kept as profit',
  price_reduction_B: 'Passed to consumer prices',
  survivor_gains_B: 'Paid as raises to remaining staff',
  automation_spend_B: 'Spent on compute & automation',
  state_rate_hike_B: 'Closed by tax-rate increases',
  state_spending_cut_B: 'Closed by spending cuts',
  state_gap_B: 'Shortfall that year',
  state_gap_cum_B: 'Accumulated shortfall',
  W_survivor: 'Wage index of the still-employed (1.0 = baseline)',
  W_reab: 'Wage index of the re-employed (1.0 = baseline)',
  survivor_gain_fed_B: 'Extra federal tax from raises',
  survivor_wage_cost_B: 'What the raises cost firms',
  employment_drop_pct: 'Employment decline',
  revenue_lost_pct: 'Labor-tax revenue decline',
}

export const TORNADO_LABELS: Record<string, string> = {
  cognitive_feasibility: 'AI capability (cognitive work)',
  physical_feasibility: 'Robot capability (physical work)',
  robotics_lag: 'Robot build-out lag',
  robotics_base: 'Robot build-out growth (base)',
  adoption_end: 'How much feasible work is automated',
  ui_weeks: 'UI benefit duration',
  reabsorption_rate: 'Re-employment rate',
  reemployment_haircut: 'Re-employment wage cut',
  reab_wage_baumol: 'Re-employed wage: Baumol pull',
  reab_wage_crowding: 'Re-employed wage: crowding',
  lfp_exit_rate: 'Labor-force exit (SSDI)',
  attrition_rate: 'Natural attrition',
  survivor_elasticity: 'Wage response to slack',
  survivor_raise_ceiling: 'Raise ceiling',
  survivor_spillover_to_profit: 'Overflow raises → profit',
  retained_profit_share: 'Saved wages kept as profit',
  price_reduction_share: 'Saved wages → lower prices',
  survivor_gains_share: 'Saved wages → raises',
  auto_cost: 'Automation input costs (→ compute)',
  offshore_share: 'Compute pool offshore share',
  compute_effective_rate: 'Compute pool tax rate',
  automation_tax_rate: 'Robot tax rate',
  ubi_recapture_rate: 'UBI recapture',
  swf_profit_share: 'SWF profit share',
  fed_vat_rate: 'Federal VAT rate',
  baseline_growth_rate: 'Trend growth',
  demand_multiplier: 'Demand multiplier',
  price_passthrough: 'Price pass-through',
  productivity_passthrough: 'Productivity dividend',
  mpc: 'Household spending propensity',
  consumption_stickiness: 'Consumption stickiness',
  interest_rate: 'Interest rate on debt',
  ubi_annual: 'UBI amount',
  ssdi_annual: 'SSDI benefit level',
  state_cut_share: 'State cut share',
  state_rate_hike_cap: 'State rate-hike cap',
}
