// Loads the static Korea bundle (generated by scripts/gen_korea_bundle.py — the page shows
// nothing that file does not carry, so the site cannot disagree with the tested model).
import { useEffect, useState } from 'react'
import type { KoreaFund } from '../charts/korea'

export interface KoreaBundle {
  config: { chain: string; central: string; band: string; adoption: string }
  headlines: {
    nhi: { published_depletion: number; years_forward_central: number;
           years_forward_lo: number; years_forward_hi: number }
    nps: { published_depletion: number; pre_reform_depletion: number; bought_years: number;
           given_back_central: number; given_back_central_lo: number;
           given_back_central_hi: number; given_back_lo: number; given_back_hi: number }
    ei: { planned_2029_tn: number; shortfall_central_tn: number;
          shortfall_lo_tn: number; shortfall_hi_tn: number }
  }
  funds: { nhi: KoreaFund & { source: string }; nps: KoreaFund & { source: string };
           ei: KoreaFund & { source: string } }
  composition: {
    central_2035: Record<string, number>
    white_collar_only: Record<string, number>
    elementary_only: Record<string, number>
  }
  sources: { name: string; cite: string }[]
}

export function useKoreaData() {
  const [bundle, setBundle] = useState<KoreaBundle | null>(null)
  const [failed, setFailed] = useState(false)
  useEffect(() => {
    let gone = false
    fetch('/data/korea.json')
      .then((r) => {
        if (!r.ok) throw new Error(String(r.status))
        return r.json()
      })
      .then((j) => { if (!gone) setBundle(j as KoreaBundle) })
      .catch(() => { if (!gone) setFailed(true) })
    return () => { gone = true }
  }, [])
  return { bundle, failed }
}
