"""Verified fact sheet for short-form writing — docs/research/brief-numbers.md.

A two-page brief, a slide, or a funding proposal needs perhaps forty numbers. Hunting them out of
a 12,000-word report invites two failures: quoting a figure the model no longer produces, and
quoting one whose caveat got left behind. So this generates the sheet from the same
manifest.json the report resolves against, with the dotted path beside every value — paste the
number, and the path tells you where to re-check it.

FAILS LOUD on any path the manifest does not have, exactly as the docx builder does: a fact sheet
that silently drops a row is worse than no fact sheet.

Sources: docs/report/artifacts/manifest.json (model + validation + screening) and
docs/research/policy-sweep/*.csv (the paired policy sweep). Regenerate after either changes.

Usage:  .venv/bin/python scripts/brief_numbers.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs" / "report" / "artifacts" / "manifest.json"
SWEEP = ROOT / "docs" / "research" / "policy-sweep"
OUT = ROOT / "docs" / "research" / "brief-numbers.md"

# (label, dotted manifest path, format spec, caveat//context). Format "" means render as-is.
ROWS: list[tuple[str, str, str, str]] = [
    # ---- scale of the baseline the deltas are measured against
    ("Federal revenue baseline", "baselines.fed_revenue0_B", ",.0f",
     "$B/yr. Every federal % figure is a share of this."),
    ("State+local revenue baseline", "baselines.state_revenue0_B", ",.0f", "$B/yr."),
    ("Federal deficit baseline", "baselines.fed_deficit0_B", ",.0f",
     "$B/yr, CBO. Deltas are ON TOP of this."),

    # ---- the scenario span: mildest and harshest of the twelve
    ("Acemoglu-Modest: employment drop", "presets.acemoglu-modest.final.employment_drop_pct", ".0f",
     "% at year 10. The mildest of the twelve presets."),
    ("Acemoglu-Modest: net fiscal impact", "presets.acemoglu-modest.final.net_fiscal_impact_B",
     "+,.0f", "$B, final year. POSITIVE = the balance improves — at this mildness the recovery "
     "channels outweigh the losses."),
    ("Korinek-Suh AGI-5y: employment drop", "presets.agi-5y.final.employment_drop_pct", ".0f",
     "% at year 10. The stress case."),
    ("Korinek-Suh AGI-5y: net fiscal impact", "presets.agi-5y.final.net_fiscal_impact_B", "+,.0f",
     "$B, final year. Negative = the balance worsens."),
    ("Korinek-Suh AGI-5y: cumulative debt", "presets.agi-5y.final.fed_debt_B", ",.0f",
     "$B added over the horizon."),
    ("Windfall-Medium: 10y total revenue", "presets.windfall-medium.cumulative.cum10y_total_revenue_pct",
     ".2f", "%. The direct comparator — set against their −2.8% in §9.1."),

    # ---- validation: the disagreements, stated as disagreements
    ("RAND replication: our federal revenue", "validation.rand_s3.fed_rev_pct_y10", ".1f",
     "% below baseline at year 10, our accounting, against their −25%."),
    ("RAND replication: price-adjusted", "validation.rand_s3.fed_rev_pct_y10_nominal_adj", ".1f",
     "% once revenue is scaled by our price level — the like-for-like number."),
    ("Acemoglu GDP check", "validation.acemoglu_gdp.y10_gdp_gain_pct", ".2f",
     "% real output gain at year 10, inside his ~1.1% upper bound."),

    # ---- global screening (policy SAMPLED — see the caveat, it matters)
    ("Screening: sample size", "screening.config.n", ",",
     "Latin hypercube points over 26 dimensions, every one passing C1-C8."),
    ("Screening: worlds that improve", "screening.regimes.improves_pct", ".1f",
     "%. NB policy is sampled here, so the rest of this block mixes AI harm with UBI outlay."),
    ("Screening: median deficit change", "screening.deficit_delta_final_B.p50", ",.0f",
     "$B. NOT the AI number — see the policy-pinned figure below, which is the honest one."),
    ("Screening: invariant failures", "screening.checks.invariant_failures", ",",
     "Out of every sampled point."),
]


def resolve(manifest: dict, path: str):
    node = manifest
    for part in path.split("."):
        if not isinstance(node, dict) or part not in node:
            sys.exit(f"manifest path not found: {path!r} (failed at {part!r}) — "
                     "regenerate with scripts/report_artifacts.py or fix ROWS")
        node = node[part]
    return node


def main() -> None:
    if not MANIFEST.exists():
        sys.exit(f"{MANIFEST} absent — run scripts/report_artifacts.py")
    manifest = json.loads(MANIFEST.read_text())

    lines = [
        "# Brief numbers — verified, with provenance",
        "",
        "Generated by `scripts/brief_numbers.py` from the same `manifest.json` the report resolves",
        "against, so these cannot drift from the model. **Regenerate after any rebuild.** The dotted",
        "path is where to re-check each value.",
        "",
        f"Model build: `{manifest.get('git_sha','?')}`, generated {manifest.get('generated','?')}; "
        f"Monte Carlo N={manifest.get('config',{}).get('n','?')}, seed "
        f"{manifest.get('config',{}).get('seed','?')}.",
        "",
        "| Figure | Value | Manifest path | Context |",
        "|---|---:|---|---|",
    ]
    for label, path, fmt, note in ROWS:
        v = resolve(manifest, path)
        val = format(v, fmt) if fmt and isinstance(v, (int, float)) else str(v)
        lines.append(f"| {label} | {val} | `{path}` | {note} |")

    # ---- the paired policy sweep: potency, which the manifest does not carry
    ladder_csv = SWEEP / "ladder.csv"
    if ladder_csv.exists():
        L = pd.read_csv(ladder_csv).set_index("regime")
        base = L.loc["no-instruments"]
        lines += [
            "",
            "## Policy-pinned figures (the honest robustness numbers)",
            "",
            "From `scripts/policy_sweep.py` — 19 uncertainty dims sampled, policy PINNED, so these",
            "measure AI's fiscal effect rather than the cost of a sampled UBI. Source:",
            "`docs/research/policy-sweep/ladder.csv`. Full argument and caveats in",
            "[policy-potency-and-value-of-information.md](policy-potency-and-value-of-information.md).",
            "",
            "| Figure | Value | Context |",
            "|---|---:|---|",
            f"| Worlds where the balance worsens | {base.pct_worlds_worsen:.1f}% | "
            "No automation-side instrument, no UBI. The robustness claim. |",
            f"| Median deficit change | {base.median_deficit_delta_B:,.0f} $B | "
            "Final year, year 10. Use THIS, not the screening median. |",
        ]
        for arm, desc in (("status-quo", "10% compute tax — already in the baseline"),
                          ("compute-20", "compute tax at 20%"),
                          ("compute-40", "compute tax at 40%"),
                          ("auto-50", "automation tax at 50% of the capacity bound")):
            if arm in L.index:
                r = L.loc[arm]
                lines.append(f"| {desc} | {r.median_pct_of_hole_closed:.0f}% of the hole | "
                             f"median {r.median_deficit_delta_B:,.0f} $B; fully closes it in "
                             f"{r.pct_worlds_fully_closed:.0f}% of worlds |")
        lines += ["", "**Do not quote `max-revenue` as a policy.** It taxes away all retained "
                  "automation profit net of cost — it is in the sweep as an upper bound only."]

    adopt_csv = SWEEP / "adoption.csv"
    if adopt_csv.exists():
        A = pd.read_csv(adopt_csv)
        spread = A[A.adoption_end_quintile == "max−min of medians"]
        if not spread.empty:
            s = spread.iloc[0]
            lines += [
                "",
                "## The automatic-stabiliser result",
                "",
                "Spread of the median deficit across adoption-extent quintiles — how much the",
                "outcome depends on how far automation actually goes:",
                "",
                f"- no instrument: **${float(s['no-instruments']):,.0f}B** spread",
                f"- 10% compute tax: ${float(s['status-quo']):,.0f}B",
                f"- 40% compute tax: **${float(s['compute-40']):,.0f}B** — near-flat: the tax base",
                "  grows with the harm, so the instrument hedges the dominant uncertainty.",
                "",
                "Caveat to carry with it: the hedge trades one unknown for another — under a compute",
                "tax, `auto_cost` becomes the top driver, because it sets the size of the base.",
            ]

    lines += [
        "",
        "## Credibility figures",
        "",
        "- **Nine conservation identities** asserted every period of every run, including every",
        "  Monte Carlo draw (C1 headcount, C2 disposition, C3 compute pool, C4 deflation,",
        "  C5c funded raises, C6 federal reconciliation, C-sh shareholder ledger, C6-state/C7,",
        "  C8 reduction).",
        "- **C8 is exact**: with every behavioural lever off, the multi-actor system reproduces the",
        "  static kernel bit-for-bit — float equality, differentially tested against v1.",
        "- **366 regression tests**; the artifact pipeline is seeded and re-runs deterministically.",
        "- **No preset is tuned to hit an external number.** §9 displays the disagreements with",
        "  Windfall Trust, RAND and Acemoglu and decomposes each one.",
        "",
        "## Known soft spots — fix before a reviewer finds them",
        "",
        "- The README's \"states bear an unfinanceable gap\" overstates the central case: median",
        "  cumulative state adjustment is ~$413B/10y against ~$15,026B federal.",
        "- The screening median (+$1,478B) is substantially UBI outlay, not AI. Quote the",
        "  policy-pinned median instead.",
        "- No behavioural response to the tax instruments is modelled — no offshoring, no timing",
        "  shift, no avoidance. The potency figures are therefore upper bounds.",
    ]

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}  ({len(ROWS)} manifest-resolved rows + policy sweep + credibility)")


if __name__ == "__main__":
    main()
